import Head from "next/head";
import { PageWrapper } from "./PageWrapper/PageWrapper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sarath G | Front-end Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageWrapper />
      </main>
    </>
  );
}
